// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrrtpqeqkstrokuswekv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFycnRwcWVxa3N0cm9rdXN3ZWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODIxOTcsImV4cCI6MjA1ODc1ODE5N30.4GhbvilH9rJ80NgQPwDMmTEZr2dbtwrLHndovsRHgig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);